services:
  app:
    container_name: orleans-stay-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT}
      LOGGING_LEVEL_COM_FORMATIONAPI: ${LOGGING_LEVEL_COM_FORMATIONAPI}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_WEB_EMBEDDED_TOMCAT: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_WEB_EMBEDDED_TOMCAT}
      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}
      ORLEANS_STAY_APP_JWT_SECRET: ${ORLEANS_STAY_APP_JWT_SECRET}
      ORLEANS_STAY_APP_JWT_EXPIRATIONMS: ${ORLEANS_STAY_APP_JWT_EXPIRATIONMS}
      ORLEANS_STAY_APP_JWT_EXPIRATIONNEWPASSWORDTOKENMS: ${ORLEANS_STAY_APP_JWT_EXPIRATIONNEWPASSWORDTOKENMS}
      WEB_CORS_ALLOWEDORIGINS: ${WEB_CORS_ALLOWEDORIGINS}
      WEB_CORS_ALLOWEDMETHODS: ${WEB_CORS_ALLOWEDMETHODS}
      WEB_CORS_ALLOWCREDENTIALS: ${WEB_CORS_ALLOWCREDENTIALS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}
      MAILJET_RESA_ACCEPTE_TEMPLATE_ID: ${MAILJET_RESA_ACCEPTE_TEMPLATE_ID}
      MAILJET_DEMANDE_RESA_TEMPLATE_ID: ${MAILJET_DEMANDE_RESA_TEMPLATE_ID}
      MAILJET_DEMANDE_ARRHES_TEMPLATE_ID: ${MAILJET_DEMANDE_ARRHES_TEMPLATE_ID}
      MAILJET_RESA_REFUSEE_TEMPLATE_ID: ${MAILJET_RESA_REFUSEE_TEMPLATE_ID}
      MAILJET_RESA_ANNULEE_TEMPLATE_ID: ${MAILJET_RESA_ANNULEE_TEMPLATE_ID}
      MAILJET_REINITIALISATION_MDP_TEMPLATE_ID: ${MAILJET_REINITIALISATION_MDP_TEMPLATE_ID}
      FRONTEND_URL: ${FRONTEND_URL}
      DOMAIN_EMAIL: ${DOMAIN_EMAIL}
    depends_on:
      - db

  db:
    container_name: orleans-stay-db
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: